<a href="https://colab.research.google.com/github/hodoosol/BoostCourse/blob/master/Chap3_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Mathematics for Artificial Intelligence

## 2강 : 행렬은 뭔가요 ?

- 행렬(matrix)는 벡터를 원소로 가지는 2차원 배열이다.

- numpy 에서는 행(row)가 기본 단위임을 명심하자. 즉, 행렬은 행벡터를 원소로 가지는 배열이다.

- 벡터는 소문자(x)로, 행렬은 대문자(X)로 표기한다.

- 행렬은 행과 열이라는 인덱스를 가진다. 행을 먼저, 열이 다음에 나온다. 

ex) xij = i행 j열의 원소

- 행렬의 특정 행(열)을 고정하면 행(열)벡터라고 부른다. 

ex) 어떤 행렬의 3번째 행벡터, 4번째 열벡터 등으로 표현 가능하다.

In [1]:
import numpy as np

x = np.array([[1, -2, 3], [7, 5, 0], [-2, -1, 2]])

## 전치행렬(transpose matrix)

- 전치행렬이란 행과 열의 인덱스가 바뀐 행렬이다.

- XT = (xji) 즉, m * n 행렬의 전치행렬은 n * m의 shape을 갖는다.

- 벡터에도 적용 가능하다.


## 행렬을 이해하는 방법(1)
- 벡터가 공간에서 한 점을 의미한다면 행렬은 여러 점들을 나타낸다.

- 행렬의 행벡터 xi는 i 번째 데이터를 의미한다.

- 행렬의 xij는 i번째 데이터의 j번째 변수의 값을 말한다.

- 행렬끼리 같은 모양을 가지면 덧셈, 뺄셈을 계산할 수 있다. -> 벡터의 덧셈, 뺄셈과 동일하다.

- 두 행렬의 각 인덱스 위치끼리 곱하는 성분곱(element wise product)도 벡터와 동일하다.

- 행렬의 스칼라 곱도 벡터와 차이가 없다.

aX = (axij) 모든 성분에 똑같은 숫자(스칼라)를 곱해준다.




## 행렬 곱셈 (matrix multiplication)

- 행렬 곱셈은 i번째 행벡터와 j번째 열벡터 사이의 내적을 성분으로 가지는 행렬을 계산한다.

- 따라서, 행렬곱을 하기 위해서는 X의 열의 개수와 Y의 행의 개수가 같아야 한다.

- XY != YX, 일반적인 곱셈과 달리 연산의 순서가 중요하다.

- numpy에서 행렬곱은 @ 연산을 사용한다.

In [2]:
X = np.array([[1, -2, 3], [7, 5, 0], [-2, -1, 2]])
Y = np.array([[0, 1], [1, -1], [-2, 1]])

In [3]:
X @ Y

array([[-8,  6],
       [ 5,  2],
       [-5,  1]])

## 행렬도 내적이 있을까 ?

- 넘파이의 np.inner는 i번째 행벡터와 j번째 행벡터 사이의 내적을 성분으로 가지는 행렬을 계산한다.

- 수학에서 말하는 내적과는 다르니 주의 ! 수학에서는 보통 tr(XYT)를 내적으로 계산한다.

- (나의 해석 _ 행렬곱이 행렬 X의 i번째 행벡터와 행렬 Y의 i번째 열벡터 사이의 내적을 구하는 것이라면 행렬의 내적은 X의 i번째 행벡터와 Y의 i번째 행벡터의 내적을 구하는 것이다.)

- np.inner = XYT 이다.

- 행렬의 내적을 계산하기 위해서는 두 행렬의 의 개수가 같아야 한다.


In [4]:
X = np.array([[1, -2, 3], [7, 5, 0], [-2, -1, 2]])
Y = np.array([[0, 1, -1], [1, -1, 0]])

In [5]:
np.inner(X, Y)

array([[-5,  3],
       [ 5,  2],
       [-3, -1]])

## 행렬을 이해하는 방법 (2)

- 행렬은 벡터공간에서 사용되는 연산자(operator)로 이해한다.

- 행렬곱을 통해 벡터를 다른 차원의 공간으로 보낼 수 있다.

- n * m 크기의 행렬 A에 m개의 행을 가지고 있는 열벡터 x를 곱해주면 n개의 행을 가지는 새로운 열벡터 Z를 얻을 수 있다.

- 따라서 m차원 공간에 존재하는 벡터 x를 n차원 공간의 벡터 z로 옮긴 것이다.

- 행렬곱을 통해 패턴을 추출할 수 있고 데이터를 압축할 수도 있다.

- 모든 선형변환(linear transform)은 행렬곱으로 계산할 수 있다.


## 역행렬(inverse matrix) 이해하기

- 행렬곱을 통해 다른 차원의 공간으로 보낸 벡터를 역행렬을 이용하여 다시 원래의 차원으로 돌려보낼 수 있다.

- 어떤 행렬 A의 연산을 거꾸로 되돌리는 행렬을 역행렬이라 부르고 A-1이라 표기한다.

- 역행렬은 행과 열 숫자가 같고 행렬식(determinant)가 0이 아닌 경우에만 계산할 수 있다.

- 역행렬은 n차원 공간의 벡터 z를 n차원 공간의 벡터 x로 되돌리는 연산이다.

- n = m일 때만 가능하고 행렬 A의 행렬식이 0이 되면 안된다.

- AA-1 = A-1A = 항등행렬 I

- 항등행렬이란 n * n 행렬에서 대각선은 모두 1이고, 나머지 원소는 0인 행렬이다.

- numpy에서는 np.linalg.inv()로 계산할 수 있다.

In [6]:
X = np.array([[1, -2, 3], 
              [7, 5, 0], 
              [-2, -1, 2]])

In [7]:
np.linalg.inv(X)

array([[ 0.21276596,  0.0212766 , -0.31914894],
       [-0.29787234,  0.17021277,  0.44680851],
       [ 0.06382979,  0.10638298,  0.40425532]])

In [8]:
# 컴퓨터에선 정확히 0, 1이 나오진 않고 근사치를 얻을 수 있다.
X @ np.linalg.inv(X)

array([[ 1.00000000e+00, -1.38777878e-17,  0.00000000e+00],
       [-2.22044605e-16,  1.00000000e+00, -5.55111512e-17],
       [-2.77555756e-17,  0.00000000e+00,  1.00000000e+00]])

- 만일 역행렬을 계산할 수 없다면 유사역행렬(pseudo-inverse) 또는 무어-펜로즈(Moore-Penrose) 역행렬 A+를 이용한다.

- n >= m 인 경우, A+ = (ATA)-1*AT

- n <= m 인 경우, A+ = AT(AAT)-1

- n >= m 이면 A+A = I 가 성립하고, n <= m이면 AA+ = I 만 성립한다.

In [9]:
Y = np.array([[0, -1],
              [1, -1],
              [-2, 1]])

In [10]:
# linear algebra _ pseudo inverse
np.linalg.pinv(Y)

array([[-5.00000000e-01, -3.33475900e-17, -5.00000000e-01],
       [-8.33333333e-01, -3.33333333e-01, -1.66666667e-01]])

In [11]:
np.linalg.pinv(Y) @ Y

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])

## 예제 _ 응용 1 : 연립방정식 풀기
np.linalg.pinv 를 이용하면 연립방정식의 해를 구할 수 있다.

a11x1 + a12x2 + ... + a1mxm = b1

a12x1 + a22x2 + ... + a2mxm = b2

...

an1x1 + an2x2 + ... + anmxm = bn

-> Ax = b 로 표현할 수 있다.

식의 개수 n 보다 변수의 개수 m 이 더 많기 때문에

n <= m 이면 무어-펜로즈 역행렬을 이용하여 하나의 해를 구할수 있다.

따라서 x = A+b = AT(AAT)-1b 가 된다.

--------------------------------------------------------------------------------

## 예제 _ 응용 2 : 선형회귀분석

np.linalg.pinv를 이용하면 데이터를 선형 모델(linear model)로 해석하는 선형회귀식을 찾을 수 있다.

선형회귀분석은 X와 y가 주어진 상황에서 계수 beta를 찾아야 한다.

Xbeta = y

그러나 선형회귀분석은 연립방정식과 달리 행이 더 크므로 방정식을 푸는 것은 불가능하다.

데이터를 최대한 잘 설명하는 beta를 찾는 것이 최선이다.

즉, 우리가 만든 예측 식의 값 y^과 정답 사이의 오차를 최소화해야 한다.

Xbeta = y^ (~~ y)

beta = X+(유사역행렬 X)y = (XTX)-1XTy

Moore-Penrose 역행렬을 이용하면 y에 근접하는 y^을 찾을 수 있다.

sklearn의 LinearRegression로도 선형회귀분석을 할 수 있다.

그러나 같은 방법이지만 linalg.pinv()와 LinearRegression은 결과가 다르게 된다.

왜일까 ?

LinearRegression은 y절편(intercept)의 항을 자동으로 추정해주지만

linalg.pinv()는 y절편 항을 직접 추가해야 한다.

y절편 항을 직접 추가한 linalg.pinv()의 결과는 LinearRegression의 결과와 동일하다.

